In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [17]:
df = pd.read_csv("/content/HR_Analytics.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

In [19]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,1,405,3,Male,54,3,1,Laboratory Technician,3,Single,1420,Upto 5k,25233,1,Y,No,13,3,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,4,Female,69,2,1,Sales Representative,3,Single,1200,Upto 5k,9724,1,Y,No,12,3,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,2,Male,69,3,1,Sales Representative,2,Single,1878,Upto 5k,8059,1,Y,Yes,14,3,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,Male,73,3,1,Research Scientist,4,Single,1051,Upto 5k,13493,1,Y,No,15,3,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,1,1156,3,Male,80,3,1,Laboratory Technician,3,Single,1904,Upto 5k,13556,1,Y,No,12,3,4,80,0,0,0,3,0,0,0,0.0

In [20]:
df.tail()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,1,549,1,Female,41,3,5,Manager,1,Married,19566,15k+,3854,5,Y,No,11,3,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,1,573,3,Female,80,2,3,Sales Executive,1,Married,10266,10k-15k,2845,4,Y,No,19,3,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,1,732,1,Male,84,3,2,Sales Executive,1,Single,5405,5k-10k,11924,8,Y,No,14,3,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,1,1233,2,Male,52,4,2,Sales Executive,4,Divorced,5220,5k-10k,10893,0,Y,Yes,18,3,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,1,1697,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,10k-15k,20467,3,Y,No,20,4,3,80,1,19,2,4,1,0,0,0.0

In [21]:
df.duplicated().sum()

np.int64(7)

In [22]:
duplicates = df[df.duplicated(keep=False)]

duplicates

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
210,RM1468,27,26-35,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,2,Male,87,4,2,Manufacturing Director,2,Married,6142,5k-10k,5174,1,Y,Yes,20,4,2,80,1,6,0,3,6,2,0,3.0
211,RM1468,27,26-35,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,2,Male,87,4,2,Manufacturing Director,2,Married,6142,5k-10k,5174,1,Y,Yes,20,4,2,80,1,6,0,3,6,2,0,3.0
327,RM1461,29,26-35,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,4,Female,73,2,1,Research Scientist,1,Single,3785,Upto 5k,8489,1,Y,No,14,3,2,80,0,5,3,1,5,4,0,4.0
328,RM1461,29,26-35,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,4,Female,73,2,1,Research Scientist,1,Single,3785,Upto 5k,8489,1,Y,No,14,3,2,80,0,5,3,1,5,4,0,4.0
457,RM1464,31,26-35,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,2,Male,74,3,2,Manufacturing Director,1,Single,9936,5k-10k,3787,0,Y,No,19,3,2,80,0,10,2,3,9,4,1,7.0
458,RM1464,31,26-35,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,2,Male,74,3,2,Manufacturing Director,1,Single,9936,5k-10k,3787,0,Y,No,19,3,2,80,0,10,2,3,9,4,1,7.0
654,RM1470,34,26-35,No,TravelRarely,628,Research & Development,8,3,Medical,1,2068,2,Male,82,4,2,Laboratory Technician,3,Married,4404,Upto 5k,10228,2,Y,No,12,3,1,80,0,6,3,4,4,3,1,2.0
655,RM1470,34,26-35,No,TravelRarely,628,Research & Development,8,3,Medical,1,2068,2,Male,82,4,2,Laboratory Technician,3,Married,4404,Upto 5k,10228,2,Y,No,12,3,1,80,0,6,3,4,4,3,1,2.0
952,RM1463,39,36-45,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,2,Female,60,2,4,Sales Executive,4,Married,12031,10k-15k,8828,0,Y,No,11,3,1,80,1,21,2,2,20,9,9,6.0
954,RM1463,39,36-45,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,2,Female,60,2,4,Sales Executive,4,Married,12031,10k-15k,8828,0,Y,No,11,3,1,80,1,21,2,2,20,9,9,6.0
1304,RM1469,49,46-55,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,4,Male,63,2,2,Sales Executive,2,Married,5390,5k-10k,13243,2,Y,No,14,3,4,80,0,17,3,2,9,6,0,8.0
1305,RM1469,49,46-55,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,4,Male,63,2,2,Sales Executive,2,Married,5390,5k-10k,13243,2,Y,No,14,3,4,80,0,17,3,2,9,6,0,8.0
1335,RM1462,50,46-55,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,4,Male,39,2,3,Sales Executive,1,Divorced,10854,10k-15k,16586,4,Y,Yes,13,3,2,80,1,20,3,3,3,2,2,0.0
1336,RM1462,50,46-55,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,4,Male,39,2,3,Sales Executive,1,Divorced,10854,10k-15k,16586,4,Y,Yes,13,3,2,80,1,20,3,3,3,2,2,0.0

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [27]:
df[df['YearsWithCurrManager'].isnull()]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
28,RM024,21,18-25,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,3,Male,96,3,1,Research Scientist,4,Single,1232,Upto 5k,19281,1,Y,No,14,3,4,80,0,0,6,3,0,0,0,NaN
31,RM363,21,18-25,No,Non-Travel,895,Sales,9,2,Medical,1,484,1,Male,39,3,1,Sales Representative,4,Single,2610,Upto 5k,2851,1,Y,No,24,4,3,80,0,3,3,2,3,2,2,NaN
45,RM207,22,18-25,No,Travel_Rarely,1136,Research & Development,5,3,Life Sciences,1,284,4,Male,60,4,1,Research Scientist,2,Divorced,2328,Upto 5k,12392,1,Y,Yes,16,3,1,80,1,4,2,2,4,2,2,NaN
99,RM139,25,18-25,No,Travel_Rarely,959,Sales,28,3,Life Sciences,1,183,1,Male,41,2,2,Sales Executive,3,Married,8639,5k-10k,24835,2,Y,No,18,3,4,80,0,6,3,3,2,2,2,NaN
100,RM256,25,18-25,No,Travel_Rarely,685,Research & Development,1,3,Life Sciences,1,350,1,Female,62,3,2,Manufacturing Director,3,Married,4898,Upto 5k,7505,0,Y,No,12,3,4,80,2,5,3,3,4,2,1,NaN
103,RM406,25,18-25,Yes,Travel_Rarely,688,Research & Development,3,3,Medical,1,538,1,Male,91,3,1,Laboratory Technician,1,Married,4031,Upto 5k,9396,5,Y,No,13,3,3,80,1,6,5,3,2,2,0,NaN
222,RM405,28,26-35,No,Travel_Rarely,1300,Research & Development,17,2,Medical,1,536,3,Male,79,3,2,Laboratory Technician,1,Divorced,4558,Upto 5k,13535,1,Y,No,12,3,4,80,1,10,2,3,10,0,1,NaN
262,RM072,29,26-35,No,Travel_Rarely,1328,Research & Development,2,3,Life Sciences,1,94,3,Male,76,3,1,Research Scientist,2,Married,2703,Upto 5k,4956,0,Y,No,23,4,4,80,1,6,3,3,5,4,0,NaN
264,RM206,29,26-35,Yes,Travel_Rarely,121,Sales,27,3,Marketing,1,283,2,Female,35,3,3,Sales Executive,4,Married,7639,5k-10k,24525,1,Y,No,22,4,4,80,3,10,3,2,10,4,1,NaN
268,RM253,29,26-35,No,Travel_Rarely,665,Research & Development,15,3,Life Sciences,1,346,3,Male,60,3,1,Research Scientist,4,Single,2340,Upto 5k,22673,1,Y,No,19,3,1,80,0,6,1,3,6,5,1,NaN
269,RM255,29,26-35,No,Travel_Rarely,1247,Sales,20,2,Marketing,1,349,4,Male,45,3,2,Sales Executive,4,Divorced,6931,5k-10k,10732,2,Y,No,14,3,4,80,1,10,2,3,3,2,0,NaN
329,RM008,30,26-35,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,4,Male,67,3,1,Laboratory Technician,3,Divorced,2693,Upto 5k,13335,1,Y,No,22,4,2,80,1,1,2,3,1,0,0,NaN
336,RM140,30,26-35,No,Travel_Rarely,1240,Human Resources,9,3,Human Resources,1,184,3,Male,48,3,2,Human Resources,4,Married,6347,5k-10k,13982,0,Y,Yes,19,3,4,80,0,12,2,1,11,9,4,NaN
337,RM144,30,26-35,No,Travel_Rarely,438,Research & Development,18,3,Life Sciences,1,194,1,Female,75,3,1,Research Scientist,3,Single,2632,Upto 5k,23910,1,Y,No,14,3,3,80,0,5,4,2,5,4,0,NaN
338,RM146,30,26-35,No,Travel_Rarely,201,Research & Development,5,3,Technical Degree,1,197,4,Female,84,3,1,Research Scientist,1,Divorced,3204,Upto 5k,10415,5,Y,No,14,3,4,80,1,8,3,3,3,2,2,NaN
339,RM147,30,26-35,No,Travel_Rarely,1427,Research & Development,2,1,Medical,1,198,2,Male,35,2,1,Laboratory Technician,4,Single,2720,Upto 5k,11162,0,Y,No,13,3,4,80,0,6,3,3,5,3,1,NaN
391,RM073,31,26-35,No,Travel_Rarely,1082,Research & Development,1,4,Medical,1,95,3,Male,87,3,1,Research Scientist,2,Single,2501,Upto 5k,18775,1,Y,No,17,3,2,80,0,1,4,3,1,1,1,NaN
392,RM076,31,26-35,No,Travel_Rarely,746,Research & Development,8,4,Life Sciences,1,98,3,Female,61,3,2,Manufacturing Director,4,Single,4424,Upto 5k,20682,1,Y,No,23,4,4,80,0,11,2,3,11,7,1,NaN
461,RM027,32,26-35,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,2,Female,72,1,1,Research Scientist,1,Single,3919,Upto 5k,4681,1,Y,Yes,22,4,2,80,0,10,5,3,10,2,6,NaN
463,RM074,32,26-35,No,Travel_Rarely,548,Research & Development,1,3,Life Sciences,1,96,2,Male,66,3,2,Research Scientist,2,Married,6220,5k-10k,7346,1,Y,No,17,3,2,80,2,10,3,3,10,4,0,NaN
466,RM141,32,26-35,Yes,Travel_Rarely,1033,Research & Development,9,3,Medical,1,190,1,Female,41,3,1,Laboratory Technician,1,Single,4200,Upto 5k,10224,7,Y,No,22,4,1,80,0,10,2,4,5,4,0,NaN
467,RM145,32,26-35,No,Travel_Frequently,689,Sales,9,2,Medical,1,195,4,Male,35,1,2,Sales Executive,4,Divorced,4668,Upto 5k,22812,0,Y,No,17,3,4,80,3,9,2,4,8,7,0,NaN
470,RM211,32,26-35,Yes,Travel_Rarely,1045,Sales,4,4,Medical,1,291,4,Male,32,1,3,Sales Executive,4,Married,10400,10k-15k,25812,1,Y,No,11,3,3,80,0,14,2,2,14,8,9,NaN
521,RM031,33,26-35,No,Travel_Rarely,924,Research & Development,2,3,Medical,1,39,3,Male,78,3,1,Laboratory Technician,4,Single,2496,Upto 5k,6670,4,Y,No,11,3,4,80,0,7,3,3,1,1,0,NaN
579,RM023,34,26-35,No,TravelRarely,419,Research & Development,7,4,Life Sciences,1,28,1,Female,53,3,3,Research Director,2,Single,11994,10k-15k,21293,0,Y,No,11,3,3,80,0,13,4,3,12,6,2,NaN
580,RM025,34,26-35,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,2,Male,83,3,1,Research Scientist,1,Single,2960,Upto 5k,17102,2,Y,No,11,3,3,80,0,8,2,3,4,2,1,NaN
664,RM077,35,26-35,No,Travel_Rarely,776,Sales,1,4,Marketing,1,100,3,Male,32,2,2,Sales Executive,1,Single,4312,Upto 5k,23016,0,Y,No,14,3,2,80,0,16,2,3,15,13,2,NaN
739,RM070,36,36-45,Yes,Travel_Rarely,318,Research & Development,9,3,Medical,1,90,4,Male,79,2,1,Research Scientist,3,Married,3388,Upto 5k,21777,0,Y,Yes,17,3,1,80,1,2,0,2,1,0,0,NaN
740,RM075,36,36-45,No,Travel_Rarely,132,Research & Development,6,3,Life Sciences,1,97,2,Female,55,4,1,Laboratory Technician,4,Married,3038,Upto 5k,22002,3,Y,No,12,3,2,80,0,5,3,3,1,0,0,NaN
745,RM208,36,36-45,No,Travel_Frequently,635,Research & Development,18,1,Medical,1,286,2,Female,73,3,1,Laboratory Technician,4,Single,2153,Upto 5k,7703,1,Y,No,13,3,1,80,0,8,2,3,8,1,1,NaN
751,RM359,36,36-45,No,Non-Travel,845,Sales,1,5,Medical,1,479,4,Female,45,3,2,Sales Executive,4,Single,6653,5k-10k,15276,4,Y,No,15,3,2,80,0,7,6,3,1,0,0,NaN
752,RM360,36,36-45,No,Travel_Frequently,541,Sales,3,4,Medical,1,481,1,Male,48,2,3,Sales Executive,4,Married,9699,5k-10k,7246,4,Y,No,11,3,1,80,1,16,2,3,13,9,1,NaN
814,RM249,37,36-45,No,Travel_Rarely,1017,Research & Development,1,2,Medical,1,340,3,Female,83,2,1,Research Scientist,1,Married,3920,Upto 5k,18697,2,Y,No,14,3,1,80,1,17,2,2,3,1,0,NaN
815,RM251,37,36-45,Yes,Travel_Frequently,504,Research & Development,10,3,Medical,1,342,1,Male,61,3,3,Manufacturing Director,3,Divorced,10048,10k-15k,22573,6,Y,No,11,3,2,80,2,17,5,3,1,0,0,NaN
854,RM009,38,36-45,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,4,Male,44,2,3,Manufacturing Director,3,Single,9526,5k-10k,8787,0,Y,No,21,4,2,80,0,10,2,3,9,7,1,NaN
858,RM143,38,36-45,No,Travel_Rarely,364,Research & Development,3,5,Technical Degree,1,193,4,Female,32,3,2,Research Scientist,3,Single,4317,Upto 5k,2302,3,Y,Yes,20,4,2,80,0,19,2,3,3,2,2,NaN
915,RM252,39,36-45,No,Travel_Frequently,505,Research & Development,2,4,Technical Degree,1,343,3,Female,64,3,3,Healthcare Representative,3,Single,10938,10k-15k,6420,0,Y,No,25,4,4,80,0,20,1,3,19,6,11,NaN
961,RM209,40,36-45,No,Non-Travel,1151,Research & Development,9,5,Life Sciences,1,287,4,Male,63,2,2,Healthcare Representative,4,Married,4876,Upto 5k,14242,9,Y,No,14,3,4,80,1,5,5,1,3,2,0,NaN
963,RM258,40,36-45,No,Travel_Rarely,1416,Research & Development,2,2,Medical,1,352,1,Male,49,3,5,Research Director,3,Divorced,19436,15k+,5949,0,Y,No,19,3,4,80,1,22,5,3,21,7,3,NaN
965,RM362,40,36-45,No,Travel_Rarely,1171,Research & Development,10,4,Life Sciences,1,483,4,Female,46,4,1,Laboratory Technician,3,Married,2213,Upto 5k,22495,3,Y,Yes,13,3,3,80,1,10,3,3,7,7,1,NaN
1025,RM404,41,36-45,No,Travel_Rarely,645,Sales,1,3,Marketing,1,534,2,Male,49,4,3,Sales Executive,1,Married,8392,5k-10k,19566,1,Y,No,16,3,3,80,1,10,2,3,10,7,0,NaN
1053,RM028,42,36-45,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,3,Male,48,3,2,Sales Executive,2,Married,6825,5k-10k,21173,0,Y,No,11,3,4,80,1,10,2,3,9,7,4,NaN
1056,RM254,42,36-45,No,Travel_Rarely,916,Research & Development,17,2,Life Sciences,1,347,4,Female,82,4,2,Research Scientist,1,Single,6545,5k-10k,23016,3,Y,Yes,13,3,3,80,0,10,1,3,3,2,0,NaN
1057,RM257,42,36-45,No,Travel_Rarely,269,Research & Development,2,3,Medical,1,351,4,Female,56,2,1,Laboratory Technician,1,Divorced,2593,Upto 5k,8007,0,Y,Yes,11,3,3,80,1,10,4,3,9,6,7,NaN
1131,RM029,44,36-45,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,1,Female,42,2,3,Healthcare Representative,4,Married,10248,10k-15k,2094,3,Y,No,14,3,4,80,1,24,4,3,22,6,5,NaN
1165,RM078,45,36-45,No,Travel_Rarely,193,Research & Development,6,4,Other,1,101,4,Male,52,3,3,Research Director,1,Married,13245,10k-15k,15067,4,Y,Yes,14,3,2,80,0,17,3,4,0,0,0,NaN
1166,RM142,45,36-45,No,Travel_Rarely,1316,Research & Development,29,3,Medical,1,192,3,Male,83,3,1,Research Scientist,4,Single,3452,Upto 5k,9752,5,Y,No,13,3,2,80,0,9,2,2,6,5,0,NaN
1172,RM250,45,36-45,No,Travel_Frequently,1199,Research & Development,7,4,Life Sciences,1,341,1,Male,77,4,2,Manufacturing Director,3,Married,6434,5k-10k,5118,4,Y,No,17,3,4,80,1,9,1,3,3,2,0,NaN
1176,RM408,45,36-45,No,Travel_Rarely,192,Research & Development,10,2,Life Sciences,1,544,1,Male,69,3,1,Research Scientist,4,Married,2654,Upto 5k,9655,3,Y,No,21,4,4,80,2,8,3,2,2,2,0,NaN
1205,RM030,46,46-55,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,2,Female,83,3,5,Manager,1,Single,18947,15k+,22822,3,Y,No,12,3,4,80,0,22,2,2,2,2,2,NaN
1211,RM210,46,46-55,No,Travel_Rarely,644,Research & Development,1,4,Medical,1,288,4,Male,97,3,3,Healthcare Representative,1,Divorced,9396,5k-10k,12368,7,Y,No,16,3,3,80,1,17,3,3,4,2,0,NaN
1345,RM259,51,46-55,No,Travel_Rarely,833,Research & Development,1,3,Life Sciences,1,353,3,Male,96,3,1,Research Scientist,4,Married,2723,Upto 5k,23231,1,Y,No,11,3,2,80,0,1,0,2,1,0,0,NaN
1360,RM407,52,46-55,No,Travel_Rarely,319,Research & Development,3,3,Medical,1,543,4,Male,39,2,3,Manufacturing Director,3,Married,7969,5k-10k,19609,2,Y,Yes,14,3,3,80,0,28,4,3,5,4,0,NaN
1375,RM026,53,46-55,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,3,Female,58,3,5,Manager,3,Divorced,19094,15k+,10735,4,Y,No,11,3,4,80,1,26,3,2,14,13,4,NaN
1448,RM361,57,55+,No,Travel_Rarely,593,Research & Development,1,4,Medical,1,482,4,Male,88,3,2,Healthcare Representative,3,Married,6755,5k-10k,2967,2,Y,No,11,3,3,80,0,15,2,3,3,2,1,NaN
1465,RM007,59,55+,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,3,Female,81,4,1,Laboratory Technician,1,Married,2670,Upto 5k,9964,4,Y,Yes,20,4,1,80,3,12,3,2,1,0,0,NaN
1467,RM071,59,55+,No,Travel_Frequently,1225,Sales,1,1,Life Sciences,1,91,1,Female,57,2,2,Sales Executive,3,Single,5473,5k-10k,24668,7,Y,No,11,3,4,80,0,20,2,2,4,3,1,NaN

In [28]:
df['YearsWithCurrManager'] = (
    df.groupby('JobRole')['YearsWithCurrManager']
      .transform(lambda x: x.fillna(x.median()))
)

A Sales Executive and Research Director may have very different manager-tenure patterns.

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1473 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1473 non-null   object
 1   Age                       1473 non-null   int64
 2   AgeGroup                  1473 non-null   object
 3   Attrition                 1473 non-null   object
 4   BusinessTravel            1473 non-null   object
 5   DailyRate                 1473 non-null   int64
 6   Department                1473 non-null   object
 7   DistanceFromHome          1473 non-null   int64
 8   Education                 1473 non-null   int64
 9   EducationField            1473 non-null   object
 10  EmployeeCount             1473 non-null   int64
 11  EmployeeNumber            1473 non-null   int64
 12  EnvironmentSatisfaction   1473 non-null   int64
 13  Gender                    1473 non-null   object
 14  HourlyRate                1473 non-null   int64
 15  JobInvolvement            1473 non-null   int64
 16  JobLevel                  1473 non-null   int64
 17  JobRole                   1473 non-null   object
 18  JobSatisfaction           1473 non-null   int64
 19  MaritalStatus             1473 non-null   object
 20  MonthlyIncome             1473 non-null   int64
 21  SalarySlab                1473 non-null   object
 22  MonthlyRate               1473 non-null   int64
 23  NumCompaniesWorked        1473 non-null   int64
 24  Over18                    1473 non-null   object
 25  OverTime                  1473 non-null   object
 26  PercentSalaryHike         1473 non-null   int64
 27  PerformanceRating         1473 non-null   int64
 28  RelationshipSatisfaction  1473 non-null   int64
 29  StandardHours             1473 non-null   int64
 30  StockOptionLevel          1473 non-null   int64
 31  TotalWorkingYears         1473 non-null   int64
 32  TrainingTimesLastYear     1473 non-null   int64
 33  WorkLifeBalance           1473 non-null   int64
 34  YearsAtCompany            1473 non-null   int64
 35  YearsInCurrentRole        1473 non-null   int64
 36  YearsSinceLastPromotion   1473 non-null   int64
 37  YearsWithCurrManager      1473 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 448.8+ KB

In [25]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1473.000000,1473.000000,1473.000000,1473.000000,1473.0,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.0,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1416.000000
mean,36.917176,802.659878,9.196877,2.911066,1.0,1026.975560,2.723693,65.833673,2.729803,2.063815,2.728445,6500.228785,14321.376103,2.693143,15.212492,3.153428,2.712152,80.0,0.793618,11.277665,2.800407,2.761711,7.004752,4.228106,2.183978,4.117232
std,9.130690,403.245460,8.107754,1.024612,0.0,603.223162,1.093006,20.350032,0.712115,1.106429,1.103163,4706.053923,7115.540450,2.496914,3.657230,0.360522,1.081575,0.0,0.851493,7.776228,1.289411,0.705838,6.121004,3.621096,3.220301,3.559344
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,492.000000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,8053.000000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1024.000000,3.000000,66.000000,3.000000,2.000000,3.000000,4908.000000,14242.000000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1558.000000,4.000000,83.000000,3.000000,3.000000,4.000000,8380.000000,20467.000000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [30]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print("-"*50)

EmpID
1470
--------------------------------------------------
Age
43
--------------------------------------------------
AgeGroup
5
--------------------------------------------------
Attrition
2
--------------------------------------------------
BusinessTravel
4
--------------------------------------------------
DailyRate
886
--------------------------------------------------
Department
3
--------------------------------------------------
DistanceFromHome
29
--------------------------------------------------
Education
5
--------------------------------------------------
EducationField
6
--------------------------------------------------
EmployeeCount
1
--------------------------------------------------
EmployeeNumber
1470
--------------------------------------------------
EnvironmentSatisfaction
4
--------------------------------------------------
Gender
2
--------------------------------------------------
HourlyRate
71
--------------------------------------------------
JobInvolvement
4
--------------------------------------------------
JobLevel
5
--------------------------------------------------
JobRole
9
--------------------------------------------------
JobSatisfaction
4
--------------------------------------------------
MaritalStatus
3
--------------------------------------------------
MonthlyIncome
1349
--------------------------------------------------
SalarySlab
4
--------------------------------------------------
MonthlyRate
1427
--------------------------------------------------
NumCompaniesWorked
10
--------------------------------------------------
Over18
1
--------------------------------------------------
OverTime
2
--------------------------------------------------
PercentSalaryHike
15
--------------------------------------------------
PerformanceRating
2
--------------------------------------------------
RelationshipSatisfaction
4
--------------------------------------------------
StandardHours
1
--------------------------------------------------
StockOptionLevel
4
--------------------------------------------------
TotalWorkingYears
40
--------------------------------------------------
TrainingTimesLastYear
7
--------------------------------------------------
WorkLifeBalance
4
--------------------------------------------------
YearsAtCompany
37
--------------------------------------------------
YearsInCurrentRole
19
--------------------------------------------------
YearsSinceLastPromotion
16
--------------------------------------------------
YearsWithCurrManager
18
--------------------------------------------------

In [31]:
df.drop(
    columns=[
        'EmployeeCount',
        'Over18',
        'StandardHours'
    ],
    inplace=True
)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1473 entries, 0 to 1479
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1473 non-null   object
 1   Age                       1473 non-null   int64
 2   AgeGroup                  1473 non-null   object
 3   Attrition                 1473 non-null   object
 4   BusinessTravel            1473 non-null   object
 5   DailyRate                 1473 non-null   int64
 6   Department                1473 non-null   object
 7   DistanceFromHome          1473 non-null   int64
 8   Education                 1473 non-null   int64
 9   EducationField            1473 non-null   object
 10  EmployeeNumber            1473 non-null   int64
 11  EnvironmentSatisfaction   1473 non-null   int64
 12  Gender                    1473 non-null   object
 13  HourlyRate                1473 non-null   int64
 14  JobInvolvement            1473 non-null   int64
 15  JobLevel                  1473 non-null   int64
 16  JobRole                   1473 non-null   object
 17  JobSatisfaction           1473 non-null   int64
 18  MaritalStatus             1473 non-null   object
 19  MonthlyIncome             1473 non-null   int64
 20  SalarySlab                1473 non-null   object
 21  MonthlyRate               1473 non-null   int64
 22  NumCompaniesWorked        1473 non-null   int64
 23  OverTime                  1473 non-null   object
 24  PercentSalaryHike         1473 non-null   int64
 25  PerformanceRating         1473 non-null   int64
 26  RelationshipSatisfaction  1473 non-null   int64
 27  StockOptionLevel          1473 non-null   int64
 28  TotalWorkingYears         1473 non-null   int64
 29  TrainingTimesLastYear     1473 non-null   int64
 30  WorkLifeBalance           1473 non-null   int64
 31  YearsAtCompany            1473 non-null   int64
 32  YearsInCurrentRole        1473 non-null   int64
 33  YearsSinceLastPromotion   1473 non-null   int64
 34  YearsWithCurrManager      1473 non-null   float64
dtypes: float64(1), int64(23), object(11)
memory usage: 414.3+ KB